### ISSUE TITLE
Why you don`t use SETEX in redis?

### ISSUE THREAD

**Issue by nicola-spb** [gojek-engineering/go-ratelimit#3]
```
	conn.Send("MULTI")
	conn.Send("SET", key, 1)
	conn.Send("EXPIRE", key, ttl)

	_, err := conn.Do("EXEC")
```

**Comment by rShetty** [comment]
@nicola-spb Thanks for this. Will surely look into this.

One more thing, in the `Run` method we want to increment the count every time. `SET` will just set it to a particular value.
